Add whoami command
neofinancial/awsx pull request #37
Opened 2021-10-16 21:14 UTC by dadair-ca

- Adds a `whoami` command with incremental improvements over the existing `status` command.
- Deprecates the `status` command so `awsx help` redirects to `whoami`.

```
Account     -> 111122223333
Aliases     -> foo
Arn         -> arn:aws:sts::111122223333:assumed-role/bar/aws-sdk-js-1635307985473
AssumedRole -> bar
Profile     -> foo
Region      -> ca-central-1
UserId      -> AAAABBBBCCCCDDDDEEEEF:aws-sdk-js-1635307985473
```

2021-10-27 19:48 UTC, usernameseb submitted a review, later dismissed

2021-11-25 16:44 UTC, MaxGoo requested changes
I get pinged for this every day so I'm requesting changes until you deal with the other requested changes :)

2021-11-25 17:39 UTC, usernameseb approved these changes

2021-11-25 21:01 UTC, MaxGoo approved these changes

2021-11-30 21:33 UTC, iansu approved these changes

2021-12-01 18:12 UTC, merged