added code coverage
neofinancial/awsx pull request #41
Opened 2022-03-01 23:25 UTC by neo-anand-patel

Ticket:
> https://app.shortcut.com/neofinancial/story/88445/add-code-coverage-to-all-dx-projects

Changes Made:
> Added code coverage by configuring GitHub workflow

2022-03-02 22:38 UTC, leah-is-offline approved these changes
looks good. codecov warnings should go away when endpoint is changes in repo settings

2022-03-02 23:30 UTC, rogersnick approved these changes

2022-03-03 00:36 UTC, iansu requested changes

2022-03-03 00:36 UTC, iansu commented on .github/workflows/ci.yml
>        - name: Upload coverage
Maybe call this one `Codecov` so we can distinguish the two better

2022-03-03 00:36 UTC, iansu commented on README.md
> +[![coverage](https://coverage.neotools.ca/api/badge/master/8LyR37NYnCX435oEgidAJ3)](https://coverage.neotools.ca/coverage/neofinancial/awsx)
I'd move this to before the Codecov badge

2022-03-03 17:29 UTC, rogersnick approved these changes

2022-03-07 15:40 UTC, leah-is-offline approved these changes

2022-03-08 21:38 UTC, usernameseb submitted a review, later dismissed

2022-03-08 23:27 UTC, Shubh2022 approved these changes

2022-03-10 16:17 UTC, usernameseb approved these changes

2022-03-11 17:33 UTC, Shubh2022 approved these changes

2022-04-29 15:07 UTC, merged