Fix Errors
neofinancial/awsx pull request #44
Opened 2022-05-04 20:01 UTC by TimaJuma

2022-05-09 20:45 UTC, iansu requested changes

2022-05-09 20:45 UTC, iansu commented on src/app.ts
> +      { onCancel: () => onCancel('Aborting [choose-assume-role] profile') }
I don't think we need any message in this case

2022-05-09 20:45 UTC, iansu commented on src/app.ts
> +      { onCancel: () => onCancel('Aborting [add-profile]') }
```suggestion
      { onCancel: () => onCancel('Cancelling add profile') }
```

Update the rest of these messages to match this format

2022-05-09 20:45 UTC, iansu commented on src/lib/prompts-helper.ts
> +  console.log(chalk.red(text));
I don't think this text needs to be red. Also drop `-helper` from the name of this file.

2022-05-09 21:49 UTC, TimaJuma commented
Modified the `onCancel` messages and output color
renamed `lib/prompt-helper` to `lib/prompts`

2022-05-10 05:53 UTC, iansu requested changes

2022-05-10 05:53 UTC, iansu commented on src/lib/profile.ts
> +    throw new Error(`Invalid credentials [AccessKey] or [SecretKey]\n ${error}`);
Don't put the parameter names in brackets

2022-05-10 05:53 UTC, iansu commented on src/app.ts
> +      { onCancel: () => onCancel('Canceling remove assume profile') }
You've got a typo in this one

2022-05-10 16:03 UTC, iansu requested changes

2022-05-10 16:03 UTC, iansu commented on CHANGELOG.md
> +- Fixing [mfaArn] validation
```suggestion
## 1.4.2 (May 10, 2022)

- Fixing `mfaArn` validation
```

2022-05-10 19:30 UTC, iansu approved these changes

2022-05-10 20:04 UTC, merged